version: '3'

volumes:

  sparkCustomerDb: {}

services:

  sparkCustomerDb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: sparkcustomerdb
    ports:
      - "127.0.0.1:9999:5432"
    volumes:
      - sparkCustomerDb:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge

