
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.elias.spark;

import org.flywaydb.core.Flyway;

import com.elias.spark.Modules.DatabaseModule;
import com.elias.spark.Modules.RepositoryModule;
import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {

	public static void main(String[] args) {

		Injector injector = configure();
		var flyway = injector.getInstance(Flyway.class);
		var restServer = injector.getInstance(RestServer.class);

		flyway.migrate();
		restServer.start();
	}

	private static Injector configure() {
		return Guice.createInjector(new DatabaseModule(), new RepositoryModule());
	}
}
