
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.elias.spark;

import static spark.Spark.before;
import static spark.Spark.get;
import static spark.Spark.post;

import com.elias.spark.customer.api.CustomerController;
import com.elias.spark.shared.Filters;

public class App {
//
//	private CustomerController customerController;
//
//	@Inject
//	public App(CustomerController customerController) {
//		this.customerController = customerController;
//	}

	public static void main(String[] args) {

		before("*", Filters.addTrailingSlashes);

		get(CustomerController.PATH, CustomerController.getAll);
		post(CustomerController.PATH, CustomerController.save);
	}
}
