
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package SparkCustomerApi;

import static spark.Spark.get;

public class App {
	public static class HelloWorld {
		public static void main(String[] args) {
			get("/hello", (req, res) -> "Hello World");
		}
	}
}
